# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0004_auto_20170523_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 23, 16, 5, 46, 21600)),
        ),
    ]
